import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans bg-cyan-100 min-h-screen `}>
        <nav className="flex justify-center gap-4 bg-yellow-400 h-12 items-center text-lg">
          <Link href="/" className="text-blue-500 font-bold hover:text-cyan-300">projects</Link>
          <Link href="/create" className="text-blue-500 font-bold hover:text-cyan-300">create</Link>
          <Link href="/account" className="text-blue-500 font-bold hover:text-cyan-300">account</Link>
        </nav>
        <main className="flex justify-center items-center h-screen">
          {children}
        </main>        
        </body>
    </html>
  );
}
